"""empty message

Revision ID: 670bcb4c6c53
Revises: 6841fcb7d795
Create Date: 2023-05-21 21:33:15.531572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670bcb4c6c53'
down_revision = '6841fcb7d795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###